<?php
/**
 * Created by PhpStorm.
 * User: Sam
 * Date: 01/11/2020
 * Time: 13:40
 */
?>

<?php if (isset($this->result)): ?>
    <div class="alert alert-dismissible alert-warning">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <h4 class="alert-heading">Attention!</h4>
        <p class="mb-0">
            Erreur d'authentification!
            <?php if ($this->result->getCode() == \Rbac\Element\Result::USER_NOT_FOUND ||
                $this->result->getCode() == \Rbac\Element\Result::PASSWORD_REJECTED): ?>
                Votre login ou mot de passe est incorrect
            <?php else: ?>
                Une erreur est survenue;
            <?php endif; ?>
        </p>
    </div>
<?php endif; ?>

<?= $this->form()->opentag($this->form); ?>

<div class="form-group">
    <label for="exampleInputEmail1" class="form-label mt-4"><?= $this->formLabel($this->form->get('email')); ?></label>
    <?= $this->formElement($this->form->get('email')); ?>
</div>
<div class="form-group">
    <label for="exampleInputPassword1"
           class="form-label mt-4"><?= $this->formLabel($this->form->get('password')); ?></label>
    <?= $this->formElement($this->form->get('password')); ?>
</div>

<div class="form-check">
    <?= $this->formLabel($this->form->get('remember_me')); ?>
    <?= $this->formElement($this->form->get('remember_me')); ?>
</div>
<?= $this->formElement($this->form->get('redirect_url')); ?>
<?= $this->formElement($this->form->get('csrf')) ?>
<?= $this->formElement($this->form->get('submit')) ?>

<?= $this->form()->closeTag(); ?>







