<?php
/**
 * Created by PhpStorm.
 * User: Sam
 * Date: 01/11/2020
 * Time: 13:40
 */
?>
<?= $this->form()->opentag($this->form); ?>

<div class="form-group">
    <label for="exampleInputEmail1" class="form-label mt-4"><?= $this->formLabel($this->form->get('email')); ?></label>
    <?= $this->formElement($this->form->get('email')); ?>
</div>
<div class="form-group">
    <label for="exampleInputPassword1" class="form-label mt-4"><?= $this->formLabel($this->form->get('password')); ?></label>
    <?= $this->formElement($this->form->get('password')); ?>
</div>

<div class="form-check">
    <?= $this->formLabel($this->form->get('remember_me')); ?>
    <?= $this->formElement($this->form->get('remember_me')); ?>
</div>
<?= $this->formElement($this->form->get('redirect_url')); ?>
<?= $this->formElement($this->form->get('csrf')) ?>
<?= $this->formElement($this->form->get('submit')) ?>

<?= $this->form()->closeTag(); ?>







