<h2>Changement de votre mot de passe</h2>

<?= $this->form()->openTag($this->form); ?>


<div class="form-group">
    <?= $this->formElement($this->form->get('password')); ?>
    <?= $this->formElementErrors($this->form->get('password')); ?>
</div>

<?= $this->formElement($this->form->get('csrf')); ?>

<div class="form-group">
    <?= $this->formElement($this->form->get('submit')); ?>
</div>

<?= $this->form()->closeTag(); ?>
