<table class="table table-hover">
    <thead>
    <tr>
        <th scope="col">Entrée</th>
        <th scope="col">Valeur</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <th scope="row">id</th>
        <td><?= $user->getId(); ?></td>
    </tr>
    <tr>
        <th scope="row">Login</th>
        <td><?= $user->getLogin(); ?></td>
    </tr>
    <tr>
        <td>Email</td>
        <td><?= $user->getEmail(); ?></td>
    </tr>
    <tr>
        <td>Status</td>
        <td><?= $user->getStatus(); ?></td>
    </tr>
    <tr>
        <td>Roles</td>
        <td>
            <ul>
                <?php foreach($user->getRoles() as $role): ?>
                <li><?= $role->getName(); ?></li>
                <?php endforeach; ?>
            </ul>
        </td>
    </tr>

    </tbody>
</table>
